# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ground_control_pb2 as ground__control__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ground_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GroundControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMap = channel.unary_unary(
                '/protobufs.GroundControl/GetMap',
                request_serializer=ground__control__pb2.Empty.SerializeToString,
                response_deserializer=ground__control__pb2.TwoDimensionalIntArray.FromString,
                _registered_method=True)
        self.GetRoverMovements = channel.unary_unary(
                '/protobufs.GroundControl/GetRoverMovements',
                request_serializer=ground__control__pb2.RoverNumber.SerializeToString,
                response_deserializer=ground__control__pb2.String.FromString,
                _registered_method=True)
        self.GetMineSerialNumber = channel.unary_unary(
                '/protobufs.GroundControl/GetMineSerialNumber',
                request_serializer=ground__control__pb2.RoverNumber.SerializeToString,
                response_deserializer=ground__control__pb2.String.FromString,
                _registered_method=True)
        self.RoverStatus = channel.unary_unary(
                '/protobufs.GroundControl/RoverStatus',
                request_serializer=ground__control__pb2.Status.SerializeToString,
                response_deserializer=ground__control__pb2.Status.FromString,
                _registered_method=True)
        self.ShareMinePin = channel.unary_unary(
                '/protobufs.GroundControl/ShareMinePin',
                request_serializer=ground__control__pb2.RoverNumberWithMineSerialAndPin.SerializeToString,
                response_deserializer=ground__control__pb2.Status.FromString,
                _registered_method=True)


class GroundControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoverMovements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMineSerialNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RoverStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareMinePin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroundControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=ground__control__pb2.Empty.FromString,
                    response_serializer=ground__control__pb2.TwoDimensionalIntArray.SerializeToString,
            ),
            'GetRoverMovements': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoverMovements,
                    request_deserializer=ground__control__pb2.RoverNumber.FromString,
                    response_serializer=ground__control__pb2.String.SerializeToString,
            ),
            'GetMineSerialNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMineSerialNumber,
                    request_deserializer=ground__control__pb2.RoverNumber.FromString,
                    response_serializer=ground__control__pb2.String.SerializeToString,
            ),
            'RoverStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.RoverStatus,
                    request_deserializer=ground__control__pb2.Status.FromString,
                    response_serializer=ground__control__pb2.Status.SerializeToString,
            ),
            'ShareMinePin': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareMinePin,
                    request_deserializer=ground__control__pb2.RoverNumberWithMineSerialAndPin.FromString,
                    response_serializer=ground__control__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protobufs.GroundControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protobufs.GroundControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroundControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protobufs.GroundControl/GetMap',
            ground__control__pb2.Empty.SerializeToString,
            ground__control__pb2.TwoDimensionalIntArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoverMovements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protobufs.GroundControl/GetRoverMovements',
            ground__control__pb2.RoverNumber.SerializeToString,
            ground__control__pb2.String.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMineSerialNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protobufs.GroundControl/GetMineSerialNumber',
            ground__control__pb2.RoverNumber.SerializeToString,
            ground__control__pb2.String.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RoverStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protobufs.GroundControl/RoverStatus',
            ground__control__pb2.Status.SerializeToString,
            ground__control__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareMinePin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protobufs.GroundControl/ShareMinePin',
            ground__control__pb2.RoverNumberWithMineSerialAndPin.SerializeToString,
            ground__control__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
