# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import land_array_pb2 as land__array__pb2
import mines_pb2 as mines__pb2
import rover_mine_pin_pb2 as rover__mine__pin__pb2
import rovers_pb2 as rovers__pb2
import status_pb2 as status__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ground_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ground_controlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_map = channel.unary_unary(
                '/protobufs.ground_control/get_map',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=land__array__pb2.land_array.FromString,
                _registered_method=True)
        self.get_movements = channel.unary_unary(
                '/protobufs.ground_control/get_movements',
                request_serializer=rovers__pb2.rover_number.SerializeToString,
                response_deserializer=rovers__pb2.rover_commands.FromString,
                _registered_method=True)
        self.get_mine_serial_number = channel.unary_unary(
                '/protobufs.ground_control/get_mine_serial_number',
                request_serializer=rovers__pb2.rover_number.SerializeToString,
                response_deserializer=mines__pb2.mine_serial_number.FromString,
                _registered_method=True)
        self.rover_status = channel.unary_unary(
                '/protobufs.ground_control/rover_status',
                request_serializer=status__pb2.status.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.share_mine_pin = channel.unary_unary(
                '/protobufs.ground_control/share_mine_pin',
                request_serializer=rover__mine__pin__pb2.rover_mine_serial_pin.SerializeToString,
                response_deserializer=status__pb2.status.FromString,
                _registered_method=True)


class ground_controlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_map(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_movements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_mine_serial_number(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def rover_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def share_mine_pin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ground_controlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_map': grpc.unary_unary_rpc_method_handler(
                    servicer.get_map,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=land__array__pb2.land_array.SerializeToString,
            ),
            'get_movements': grpc.unary_unary_rpc_method_handler(
                    servicer.get_movements,
                    request_deserializer=rovers__pb2.rover_number.FromString,
                    response_serializer=rovers__pb2.rover_commands.SerializeToString,
            ),
            'get_mine_serial_number': grpc.unary_unary_rpc_method_handler(
                    servicer.get_mine_serial_number,
                    request_deserializer=rovers__pb2.rover_number.FromString,
                    response_serializer=mines__pb2.mine_serial_number.SerializeToString,
            ),
            'rover_status': grpc.unary_unary_rpc_method_handler(
                    servicer.rover_status,
                    request_deserializer=status__pb2.status.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'share_mine_pin': grpc.unary_unary_rpc_method_handler(
                    servicer.share_mine_pin,
                    request_deserializer=rover__mine__pin__pb2.rover_mine_serial_pin.FromString,
                    response_serializer=status__pb2.status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protobufs.ground_control', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protobufs.ground_control', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ground_control(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_map(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protobufs.ground_control/get_map',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            land__array__pb2.land_array.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_movements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protobufs.ground_control/get_movements',
            rovers__pb2.rover_number.SerializeToString,
            rovers__pb2.rover_commands.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_mine_serial_number(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protobufs.ground_control/get_mine_serial_number',
            rovers__pb2.rover_number.SerializeToString,
            mines__pb2.mine_serial_number.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def rover_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protobufs.ground_control/rover_status',
            status__pb2.status.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def share_mine_pin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protobufs.ground_control/share_mine_pin',
            rover__mine__pin__pb2.rover_mine_serial_pin.SerializeToString,
            status__pb2.status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
