# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ground_control.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ground_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import land_array_pb2 as land__array__pb2
import rovers_pb2 as rovers__pb2
import mines_pb2 as mines__pb2
import rover_mine_pin_pb2 as rover__mine__pin__pb2
import status_pb2 as status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ground_control.proto\x12\tprotobufs\x1a\x1bgoogle/protobuf/empty.proto\x1a\x10land_array.proto\x1a\x0crovers.proto\x1a\x0bmines.proto\x1a\x14rover_mine_pin.proto\x1a\x0cstatus.proto2\xe3\x02\n\x0eground_control\x12\x38\n\x07get_map\x12\x16.google.protobuf.Empty\x1a\x15.protobufs.land_array\x12\x43\n\rget_movements\x12\x17.protobufs.rover_number\x1a\x19.protobufs.rover_commands\x12P\n\x16get_mine_serial_number\x12\x17.protobufs.rover_number\x1a\x1d.protobufs.mine_serial_number\x12\x39\n\x0crover_status\x12\x11.protobufs.status\x1a\x16.google.protobuf.Empty\x12\x45\n\x0eshare_mine_pin\x12 .protobufs.rover_mine_serial_pin\x1a\x11.protobufs.statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ground_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GROUND_CONTROL']._serialized_start=146
  _globals['_GROUND_CONTROL']._serialized_end=501
# @@protoc_insertion_point(module_scope)
