# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ground_control.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ground_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ground_control.proto\x12\tprotobufs\"\x07\n\x05\x45mpty\"\x1a\n\x08IntArray\x12\x0e\n\x06values\x18\x01 \x03(\x05\":\n\x16TwoDimensionalIntArray\x12 \n\x03row\x18\x01 \x03(\x0b\x32\x13.protobufs.IntArray\"\x1d\n\x0bRoverNumber\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x17\n\x06String\x12\r\n\x05value\x18\x01 \x01(\t\"-\n\x06Status\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"a\n\x1fRoverNumberWithMineSerialAndPin\x12\x13\n\x0broverNumber\x18\x01 \x01(\x05\x12\x18\n\x10mineSerialNumber\x18\x02 \x01(\t\x12\x0f\n\x07minePin\x18\x03 \x01(\t2\xd0\x01\n\rGroundControl\x12=\n\x06GetMap\x12\x10.protobufs.Empty\x1a!.protobufs.TwoDimensionalIntArray\x12>\n\x11GetRoverMovements\x12\x16.protobufs.RoverNumber\x1a\x11.protobufs.String\x12@\n\x13GetMineSerialNumber\x12\x16.protobufs.RoverNumber\x1a\x11.protobufs.Stringb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ground_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=35
  _globals['_EMPTY']._serialized_end=42
  _globals['_INTARRAY']._serialized_start=44
  _globals['_INTARRAY']._serialized_end=70
  _globals['_TWODIMENSIONALINTARRAY']._serialized_start=72
  _globals['_TWODIMENSIONALINTARRAY']._serialized_end=130
  _globals['_ROVERNUMBER']._serialized_start=132
  _globals['_ROVERNUMBER']._serialized_end=161
  _globals['_STRING']._serialized_start=163
  _globals['_STRING']._serialized_end=186
  _globals['_STATUS']._serialized_start=188
  _globals['_STATUS']._serialized_end=233
  _globals['_ROVERNUMBERWITHMINESERIALANDPIN']._serialized_start=235
  _globals['_ROVERNUMBERWITHMINESERIALANDPIN']._serialized_end=332
  _globals['_GROUNDCONTROL']._serialized_start=335
  _globals['_GROUNDCONTROL']._serialized_end=543
# @@protoc_insertion_point(module_scope)
